(()=>{
 'use strict';
 const $=id=>document.getElementById(id);let cards=[...document.querySelectorAll('.design-card')],selected,opener;
 const loaded=fetch('/catalogue/designs.json').then(r=>{if(!r.ok)throw Error();return r.json()});loaded.catch(()=>{});
 function bindCard(card){card.querySelectorAll('[data-design-open]').forEach(b=>b.onclick=()=>open(b.dataset.designOpen,b));}
 document.querySelectorAll('[data-design-open]').forEach(b=>b.onclick=()=>open(b.dataset.designOpen,b));
 function addNewCards(data){
  const grid=document.querySelector('.design-grid');if(!grid)return;
  data.filter(d=>/^P\d{2}$/.test(d.id)).forEach(d=>{const card=document.createElement('article');card.className='design-card';card.id='design-'+d.id;card.dataset.designCategory=d.category;card.dataset.designSearch=(d.name+' '+d.category+' '+d.description).toLowerCase();card.innerHTML='<button type="button" class="design-picture" data-design-open="'+d.id+'" aria-label="Choose '+d.name+'"><img src="'+d.images[0].src+'" width="1200" height="1200" alt="'+d.name+' — '+d.description+'" loading="lazy"></button><div><p class="eyebrow">'+d.category+' · '+d.id+'</p><h3>'+d.name+'</h3><p>'+d.description+'</p><p class="design-quote">Personalised to order · See it with your name</p><button class="button primary" data-design-open="'+d.id+'" type="button">See it with my name →</button></div>';grid.append(card);});
  cards=[...document.querySelectorAll('.design-card')];cards.slice(-42).forEach(bindCard);const option=document.createElement('option');option.value='New product photography';option.textContent='New product photography';const select=$('design-category');if(select&&!select.querySelector('option[value="New product photography"]'))select.append(option);$('design-count').textContent=cards.length+' designs · '+data.reduce((n,d)=>n+d.images.length,0)+' images';
 }
 loaded.then(addNewCards).then(()=>{filter();linked();});
 function filter(){const q=$('design-search').value.toLowerCase().trim(),cat=$('design-category').value;let count=0;cards.forEach(c=>{c.hidden=!!((q&&!c.dataset.designSearch.includes(q))||(cat&&c.dataset.designCategory!==cat));if(!c.hidden)count++});$('design-count').textContent=count+' designs shown';$('design-empty').hidden=!!count}
 ['design-search','design-category'].forEach(id=>$(id).addEventListener('input',filter));
 function view(i){const im=selected.images[i];$('design-image').src=im.src;$('design-image').alt=selected.name+' — image '+(i+1);[...$('design-views').children].forEach((b,n)=>b.setAttribute('aria-pressed',String(i===n)))}
 async function open(id,b){try{selected=(await loaded).find(d=>d.id===id);if(!selected)return;opener=b;$('design-form').reset();$('design-ready').hidden=true;$('design-title').textContent=selected.name;$('design-code').textContent=selected.category+' · '+selected.id;$('design-description').textContent=selected.description;$('design-views').replaceChildren();selected.images.forEach((im,i)=>{if(selected.images.length===1)return;const button=document.createElement('button');button.type='button';button.textContent='View '+(i+1);button.onclick=()=>view(i);$('design-views').append(button)});view(0);$('design-dialog').showModal()}catch{$('design-count').textContent='Unable to load design details. Please reload or contact info@nameitstudio.in.'}}
 $('design-close').onclick=()=>$('design-dialog').close();$('design-dialog').addEventListener('close',()=>opener?.focus());$('design-form').addEventListener('input',()=>$('design-ready').hidden=true);$('design-form').onsubmit=e=>{e.preventDefault();const lines=['Hello Name It Studio, I would like a quote for '+selected.name+' ('+selected.id+').','Design: https://nameitstudio.in/catalogue/#design-'+selected.id,'Reference image: https://nameitstudio.in'+selected.images[0].src,'My text: '+($('design-text').value.trim()||'Please help me finalise it.'),'Preferred size: '+($('design-size').value.trim()||'Please advise.'),'Lighting: '+$('design-lighting').value,'Changes: '+($('design-notes').value.trim()||'None specified.'),'Please prepare 4 artwork options based on this design and my details, then confirm materials, size, artwork and final price, including the limited-time ₹100 discount.','Payment: 10% after design finalisation, remaining 90% on delivery. Delivery within 3–5 working days from order confirmation.'];const link=$('design-whatsapp');link.href='https://wa.me/919082405720?text='+encodeURIComponent(lines.join('\n\n'));$('design-ready').hidden=false;link.click()};
 function linked(){const match=location.hash.match(/^#design-((?:D|P)\d{2})$/);if(match)open(match[1],document.querySelector('[data-design-open="'+match[1]+'"]'))}
 window.addEventListener('hashchange',linked);linked();
})();
