(()=>{'use strict';
function nis_track_event(name,params={}){if(typeof window.gtag==='function'){window.gtag('event',name,{...params,page_path:location.pathname+location.hash});}}
document.addEventListener('click',e=>{
 const el=e.target.closest('a,button'); if(!el)return;
 const href=(el.getAttribute('href')||'').trim();
 if(href.includes('wa.me/')) nis_track_event('whatsapp_click',{link_text:(el.textContent||'').trim().slice(0,80),destination:href.split('?')[0]}); if(el.hasAttribute('data-design-options')) nis_track_event('design_options_click',{link_text:(el.textContent||'').trim().slice(0,80)});
 if(href.startsWith('tel:')) nis_track_event('phone_click',{link_text:(el.textContent||'').trim().slice(0,80)});
 if(href==='#studio'||href==='/#studio'||href.includes('#project-request')||el.hasAttribute('data-start')||el.hasAttribute('data-project')) nis_track_event('customize_click',{link_text:(el.textContent||'').trim().slice(0,80)});
 if(el.hasAttribute('data-catalogue-open')) nis_track_event('product_select',{product_id:'NIS-'+el.getAttribute('data-catalogue-open'),product_type:'priced_product'});
 if(el.hasAttribute('data-design-open')) nis_track_event('product_select',{product_id:el.getAttribute('data-design-open'),product_type:'design'});
 if(href.includes('/how-to-order/')) nis_track_event('order_guide_click',{link_text:(el.textContent||'').trim().slice(0,80)});
},true);
const more=document.getElementById('more-options');function reveal(target){if(more&&target&&more.contains(target))more.open=true}function linked(){let target;try{target=document.getElementById(decodeURIComponent(location.hash.slice(1)))}catch{}reveal(target);if(target&&more?.contains(target))requestAnimationFrame(()=>target.scrollIntoView({block:'start'}));if(document.getElementById('priced-products')){if(location.hash.startsWith('#product-')||location.hash==='#catalogue-grid')tab('priced-products');else if(location.hash.startsWith('#design-'))tab('designs')}}document.addEventListener('click',e=>{const b=e.target.closest('[data-start],[data-project]');if(b&&more)more.open=true;const a=e.target.closest('a[href^="#"]');if(a)reveal(document.getElementById(a.getAttribute('href').slice(1)))},true);function tab(id){for(const name of['designs','priced-products']){const n=document.getElementById(name);if(n)n.hidden=name!==id}document.querySelectorAll('[data-shop-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.shopTab===id)))}document.querySelectorAll('[data-shop-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.shopTab));const params=new URLSearchParams(location.search),search=document.getElementById('design-search'),category=document.getElementById('design-category');if(search&&params.has('q')){search.value=params.get('q');search.dispatchEvent(new Event('input'));const old=document.getElementById('catalogue-search');old.value=params.get('q');old.dispatchEvent(new Event('input'))}if(category&&[...category.options].some(o=>o.value===params.get('category'))){category.value=params.get('category');category.dispatchEvent(new Event('input'))}document.querySelectorAll('.shop-header nav a').forEach(a=>{if(a.getAttribute('href')===location.pathname)a.setAttribute('aria-current','page')});
function setupNavigation(){
 const header=document.querySelector('.shop-header'),nav=header?.querySelector('nav');if(!header||!nav)return;
 nav.classList.add('nis-nav');
 nav.innerHTML='<a href="/">Home</a><a href="/catalogue/">Shop</a><a href="/#project-request">Custom order</a><a href="/how-to-order/">How it works</a><a href="/#real-work">Real work</a><a href="/bulk-orders-resellers/">Bulk / Reseller</a><a href="/#contact">Contact</a>';
 const menu=document.createElement('button');menu.type='button';menu.className='nav-toggle';menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open site menu');menu.innerHTML='<span>Menu</span><span aria-hidden="true">☰</span>';nav.before(menu);
 const setOpen=open=>{header.classList.toggle('nav-open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close site menu':'Open site menu');menu.lastElementChild.textContent=open?'×':'☰'};
 menu.addEventListener('click',()=>setOpen(!header.classList.contains('nav-open')));nav.addEventListener('click',e=>{if(e.target.closest('a'))setOpen(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape')setOpen(false)});
 const path=location.pathname;nav.querySelectorAll('a').forEach(a=>{const href=a.getAttribute('href');if((href==='/'&&path==='/')||(href==='/catalogue/'&&path.startsWith('/catalogue'))||(href==='/how-to-order/'&&path.startsWith('/how-to-order')))a.setAttribute('aria-current','page')});
 if(!document.querySelector('.mobile-quick-nav')){const dock=document.createElement('div');dock.className='mobile-quick-nav';dock.setAttribute('role','navigation');dock.setAttribute('aria-label','Quick actions');dock.innerHTML='<a href="/catalogue/"><span aria-hidden="true">⌕</span>Shop</a><a href="/#project-request"><span aria-hidden="true">✎</span>Custom</a><a class="quick-whatsapp" href="https://wa.me/919082405720" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">↗</span>WhatsApp</a>';document.body.append(dock)}
}
setupNavigation();window.addEventListener('hashchange',linked);linked()})();
