#!/usr/bin/env python3
"""Build public listing pages from the current catalogue. Run after catalogue removals/updates."""
from pathlib import Path
import json,re,html
R=Path(__file__).resolve().parents[1];D=json.loads((R/'catalogue/designs.json').read_text());by={d['id']:d for d in D};E=lambda v:html.escape(str(v),quote=True);W='https://wa.me/919082405720';V='20261010-reference'
def lit(d):
 if 'lighting' in d:return d['lighting']=='With LED'
 s=d.get('productionNotes','').lower();return 'led' in s and not any(t in s for t in ['no led','without led'])
def kind(d):return 'Charcoal & engraved' if d['category']=='Engraved Mandala' else d['category']
def pic(d):return d['images'][0]['src']
def card(d):
 return f'''<article class="current-card" data-current-design="{d['id']}"><a class="current-card-image" href="{d['productUrl']}"><img src="{pic(d)}" alt="{E(d['name'])}" width="{d['images'][0]['width']}" height="{d['images'][0]['height']}" loading="lazy"><span>{'LED' if lit(d) else 'No LED'}</span></a><div class="current-card-info"><p>{E(kind(d))} · {d['id']}</p><h3><a href="{d['productUrl']}">{E(d['name'])}</a></h3><div class="card-bottom"><strong>₹{d['pricePerSqIn']} <small>/ sq in</small></strong><a href="{d['productUrl']}" aria-label="Customise {E(d['name'])}">Customise ↗</a></div></div></article>'''
def cards(items):return '<div class="current-grid">'+''.join(card(d) for d in items)+'</div>'
header=f'''<div class="studio-topbar">Made to order in Mumbai <span>Design approval first · Delivery in 3–5 working days</span><a href="tel:+919082405720">Call +91 90824 05720</a></div><header class="header shop-header"><a class="brand" href="/" aria-label="Name It Studio home"><span class="brand-icon"><img src="/assets/name-it-mark.svg" alt=""></span><span class="brand-wordmark">NAME IT STUDIO<small>YOUR NAME. YOUR STYLE.</small></span></a><form class="shop-search" action="/catalogue/" role="search"><label class="sr-only" for="shop-search">Search designs</label><input id="shop-search" name="q" type="search" placeholder="Search products…"><button type="submit">Search</button></form><a class="header-help" href="{W}" target="_blank" rel="noopener noreferrer">Let’s make it yours<strong>WhatsApp us ↗</strong></a><nav aria-label="Main navigation"><a href="/catalogue/">Shop designs</a><a href="/customize/">Customise</a><a href="/how-to-order/">How it works</a><a href="/#contact">Contact</a></nav></header>'''
footer=f'''<footer class="studio-footer" id="contact"><div class="showroom-wrap store-footer-grid"><div><h3>STORE INFORMATION</h3><a class="footer-brand" href="/">NAME IT STUDIO</a><p>Personalised acrylic, glass and charcoal nameplates. Your name. Your style. Crafted in Mumbai.</p><a href="/#real-work">See our original work →</a></div><div><h3>ORDER HELP</h3><a href="/how-to-order/">How to order</a><a href="/customize/">Customize your nameplate</a><a href="/how-to-order/">Payment & delivery</a><a href="/bulk-orders-resellers/">Bulk & reseller enquiries</a></div><div><h3>SHOP DESIGNS</h3><a href="/catalogue/">All designs</a><a href="/catalogue/?new=1#designs">New arrivals</a><a href="/acrylic-nameplates/">Acrylic nameplates</a><a href="/glass-nameplates/">Glass nameplates</a><a href="/engraved-charcoal/">Charcoal & engraved</a></div><div class="footer-contact"><h3>CONTACT US</h3><a href="mailto:info@nameitstudio.in">info@nameitstudio.in</a><a href="tel:+919082405720">Call +91 90824 05720</a><a href="{W}" target="_blank" rel="noopener noreferrer">WhatsApp to order ↗</a><p>Mumbai, India</p></div></div><div class="showroom-wrap store-copyright">© 2026 Name It Studio · Made to order · Design approval before production</div></footer>'''
def page(path,title,description,body,extra='',klass='showroom nis-luxe'):
 canonical='https://nameitstudio.in/'+path;head=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | Name It Studio</title><meta name="description" content="{E(description)}"><link rel="canonical" href="{canonical}"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/assets/fonts/fonts.css"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/shop-theme.css?v={V}"><link rel="stylesheet" href="/showroom.css?v={V}"><script async src="https://www.googletagmanager.com/gtag/js?id=G-KH9G59TVN1"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','G-KH9G59TVN1');</script><script src="/shop-theme.js?v={V}" defer></script><script src="/catalogue-sync.js?v={V}" defer></script>{extra}<link rel="stylesheet" href="/storefront-theme.css?v={V}"></head><body class="{klass}">{header}<main>{body}</main>{footer}</body></html>''';target=R/path/'index.html';target.parent.mkdir(exist_ok=True,parents=True);target.write_text(head)
def section(title,copy,items,link='/catalogue/',label='Explore all designs',id=''):
 return f'<section class="showroom-wrap browse-section"'+(f' id="{id}"' if id else '')+f'><div class="browse-heading"><div><h2>{title}</h2><p>{copy}</p></div><a class="text-link" href="{link}">{label} ↗</a></div>'+cards(items)+'</section>'
styles=[('Acrylic','acrylic-nameplates','Clean lines. Beautiful lettering.','N65'),('LED','led-nameplates','A warm welcome, day and night.','N01'),('Glass','glass-nameplates','Elegant glass. A little extra shine.','N53'),('Charcoal & engraved','engraved-charcoal','Texture, detail and depth.','N08'),('Devotional','devotional-nameplates','Made with a little more meaning.','D05'),('Business & office','business-office-signs','Your brand, beautifully displayed.','N52')]
shop='<section class="showroom-wrap browse-section" id="shop-by-style"><div class="browse-heading"><div><p class="overline">FIND YOUR LOOK</p><h2>Shop by Style</h2></div><p>A material for every entrance.<br>A design for every personality.</p></div><div class="style-grid">'+''.join(f'<a class="style-card" href="/{slug}/"><img src="{pic(by[code])}" alt="{E(name)} nameplate design" loading="lazy"><div><h3>{E(name)}</h3><p>{copy}</p><span>Explore ↗</span></div></a>' for name,slug,copy,code in styles if code in by)+'</div></section>'
hero='''<section class="showroom-hero showroom-wrap"><div class="hero-copy"><p class="overline">PERSONALISED NAMEPLATES · CRAFTED IN MUMBAI</p><h1>Your Name.<br>Your Style.<br><em>Your Entrance.</em></h1><p class="hero-description">A beautiful welcome, made just for you. Explore acrylic, glass and charcoal nameplates with your name, your style and your finish.</p><div class="actions"><a class="dark-button" href="/customize/">Customize your nameplate ↗</a><a class="text-link" href="/catalogue/">Explore designs →</a></div><p class="hero-assurance">Made to Order · Design Approval · Custom Sizes · Crafted in Mumbai</p></div><figure class="hero-photo social-banner" aria-label="Featured social media designs"><div class="social-banner-slides" aria-live="polite"><a data-banner-slide href="/engraved-charcoal/"><img src="/assets/social/charcoal-led-post.webp" alt="Name It Studio social media post featuring the charcoal tile finish LED nameplate" width="1254" height="1254" fetchpriority="high"></a><a data-banner-slide href="/glass-nameplates/" hidden><img src="/assets/social/premium-glass-post.webp" alt="Name It Studio social media post featuring the premium glass nameplate with golden letters and warm LED lighting" width="1254" height="1254" loading="lazy"></a></div><figcaption><span>From our social media</span><div class="social-banner-controls" aria-label="Choose a featured post"><button type="button" data-banner-index="0" aria-pressed="true">Charcoal LED</button><button type="button" data-banner-index="1" aria-pressed="false">Premium glass</button></div></figcaption></figure></section>'''
latest=section('New Arrivals','Discover our latest personalised nameplate designs.',[by[x] for x in ['N01','N08','N53','N65','N07','N42','N73','N18','N31','N52'] if x in by],'/catalogue/?new=1#designs','See all '+str(sum(bool(d.get('isNew')) for d in D))+' latest designs','latest-designs')
featured=section('Featured Designs','Find a design you love. We’ll personalise every detail.',[by[x] for x in ['D03','D08','D05','N07','N42','N73','N76','D06','N54','N65'] if x in by],id='best-sellers')
steps='''<section class="process-band" id="studio"><div class="showroom-wrap process-layout"><div><p class="overline">MAKE IT YOURS</p><h2>Your idea.<br>Our craft.</h2><p>Pick a design, share your name and size, then approve the artwork before we make it.</p><a class="dark-button" href="/customize/">Start customising ↗</a></div><ol><li><span>01</span><div><h3>Find your design</h3><p>Choose the material, style and lighting you love.</p></div></li><li><span>02</span><div><h3>Make it personal</h3><p>Add your name, house number, size, language and finish.</p></div></li><li><span>03</span><div><h3>Approve. Then we craft.</h3><p>Four artwork options. 30% after approval, 70% on delivery.</p></div></li></ol></div></section>'''
work='''<section class="showroom-wrap browse-section" id="real-work"><div class="browse-heading"><div><p class="overline">REAL WORK. REAL DETAILS.</p><h2>From our workshop<br>to your doorstep.</h2></div><p>Original photographs of pieces<br>we’ve crafted at Name It Studio.</p></div><div class="work-strip">'''+''.join(f'<figure><img src="/assets/real-work/name-it-studio-real-work-{i:02}.jpg" alt="Original Name It Studio workshop photo {i}" loading="lazy"><figcaption>Made to order · Mumbai</figcaption></figure>' for i in [3,7,8,11])+'''</div></section>'''
meaning=[('ganesha','Ganesha',['D05','D06','D37','N01','N18','N24','N31','N33','N53','N54','N59','N64','N75','N77']),('mahadev','Mahadev',[]),('krishna-radha-krishna','Krishna & Radha Krishna',['N23','N48']),('shree-ram-hanuman','Shree Ram & Hanuman',[]),('om-spiritual','Om & spiritual',['D38','D43','N42','N57','N73']),('ambedkar','Dr. B. R. Ambedkar',[])]
meaninghtml='<section class="showroom-wrap browse-section" id="designs-with-meaning"><div class="browse-heading"><div><p class="overline">DESIGNS WITH MEANING</p><h2>A welcome with a story.</h2></div><a class="text-link" href="'+W+'">Discuss your idea ↗</a></div><div class="meaning-links">'+''.join(f'<a href="/collections/{slug}/"><span>{E(name)}</span><span>↗</span></a>' for slug,name,_ in meaning)+'</div></section>'
form='''<section class="showroom-wrap enquiry-layout" id="quick-enquiry"><div id="project-request"><p class="overline">LET’S START WITH YOUR NAME</p><h2>Tell us what<br>you have in mind.</h2><p>Choose a design and share the basics. We’ll help you finalise the size, finish and artwork on WhatsApp.</p><a class="text-link" href="tel:+919082405720">Prefer to talk? +91 90824 05720 ↗</a></div><form id="visitor-lead-form" class="enquiry-form"><div class="enquiry-fields"><label>Material<select name="material" id="lead-material"><option value="Not sure">Help me choose</option><option>Acrylic</option><option>Glass</option><option value="Engraved Mandala">Charcoal & engraved</option></select></label><label>Design<select id="lead-design" name="design"><option value="">Recommend a design</option></select></label><label>Width (inches)<input id="lead-width" name="width" type="number" min="1" step="0.25" placeholder="15"></label><label>Height (inches)<input id="lead-height" name="height" type="number" min="1" step="0.25" placeholder="8"></label><label class="full">Name / house number on the plate<input name="plate_text" required placeholder="e.g. The Shaikhs · 1603"></label><label>Your name<input name="name" required autocomplete="name"></label><label>Phone / WhatsApp<input name="phone" required type="tel" autocomplete="tel"></label><label class="full">Area / city<input name="area" placeholder="Mumbai"></label></div><div id="lead-price-estimate" class="enquiry-estimate"></div><button class="dark-button" type="submit">Get my 4 artwork options on WhatsApp ↗</button><p class="form-note">Final price confirmed after artwork and construction approval.</p></form></section>'''
faq='''<section class="showroom-wrap home-faq" id="questions"><div><p class="overline">GOOD TO KNOW</p><h2>The details,<br>made simple.</h2></div><div><details><summary>How much does a nameplate cost?</summary><p>Acrylic: ₹10/sq in without LED, ₹12 with LED. Glass: ₹12 without LED, ₹15 with LED. Charcoal with engraved design: ₹16 without LED, ₹18 with LED. Final pricing is confirmed for your approved size and construction.</p></details><details><summary>Can I choose the language and size?</summary><p>Yes. English, Hindi and Marathi lettering, custom sizes and material-appropriate finishes are discussed before production.</p></details><details><summary>When do I pay, and when will it arrive?</summary><p>Pay 30% after design approval and 70% on delivery. Delivery is typically within 3–5 working days from order confirmation.</p></details><details><summary>Can you work from my own idea or photo?</summary><p>Yes. Send your reference image on WhatsApp and we’ll discuss how to make it.</p></details><a class="text-link" href="/how-to-order/">Read the order guide ↗</a></div></section>'''
page('', 'Custom Nameplates in Mumbai', 'Personalised acrylic, glass and charcoal nameplates. Custom sizes, four artwork options and design approval before production. Crafted in Mumbai.',hero+shop+latest+featured+steps+work+meaninghtml+form+faq,'<script src="/home.js?v='+V+'" defer></script>', 'showroom showroom-home nis-luxe')
# Category and collection pages show only actual current catalogue entries.
category_specs=[('acrylic-nameplates','Acrylic nameplates','Layered detail, clean lettering and a finish that feels like you.',lambda d:d['category']=='Acrylic'),('glass-nameplates','Glass nameplates','An elegant welcome in glass. Choose your name, size and lighting.',lambda d:d['category']=='Glass'),('engraved-charcoal','Charcoal & engraved nameplates','Texture, sculpted borders and dimensional lettering.',lambda d:d['category']=='Engraved Mandala'),('led-nameplates','LED nameplates','A warm welcome with lighting. Explore current illuminated designs.',lit),('devotional-nameplates','Devotional nameplates','Meaningful symbols and personalised details for your entrance.',lambda d:d['collection']=='Devotional décor' or d['id'] in {i for _,_,ids in meaning for i in ids}),('business-office-signs','Business & office signs','Personalised signage for your brand, office or studio.',lambda d:d['collection']=='Business signs'),('custom-logo-signs','Custom logo signs','Your own logo, lettering and dimensions. Share your artwork to get started.',lambda d:d['collection']=='Business signs')]
for slug,title,copy,filter in category_specs:
 items=[d for d in D if filter(d)];body=f'<section class="showroom-wrap listing-intro"><p class="overline">NAME IT STUDIO · MADE TO ORDER</p><h1>{title}</h1><p>{copy}</p><div class="actions"><a class="text-link" href="/catalogue/">View all designs ↗</a><a class="text-link" href="{W}">Ask us on WhatsApp ↗</a></div><p class="listing-count">{len(items)} current designs · Custom sizes · Design approval first</p></section><section class="showroom-wrap browse-section">'+cards(items)+'</section>';page(slug+'/',title,copy,body)
for slug,title,ids in meaning:
 items=[by[i] for i in ids if i in by];body=f'<section class="showroom-wrap listing-intro"><p class="overline">DESIGNS WITH MEANING</p><h1>{E(title)}</h1><p>A personalised piece with meaning. Share the artwork, name and size you have in mind.</p><a class="dark-button" href="{W}?text=I%20would%20like%20to%20discuss%20a%20{slug}%20design.">Discuss your design ↗</a></section>'
 if items:body+='<section class="showroom-wrap browse-section">'+cards(items)+'</section>'
 else:body+='<section class="showroom-wrap custom-collection"><h2>Your idea, made to order.</h2><p>Contact us with a reference image to discuss your preferred design, material and dimensions before production.</p><a class="text-link" href="/catalogue/">Explore current nameplates ↗</a></section>'
 page('collections/'+slug+'/',title+' nameplates','Explore '+title+' designs and discuss a personalised nameplate with Name It Studio.',body)
# Use the current design catalogue with one unified filter and quote flow.
body='''<section class="showroom-wrap listing-intro"><p class="overline">FIND YOUR NEXT WELCOME</p><h1>Made for your name.</h1><p>Explore our current designs. Choose the size and details that make it yours.</p><div class="actions"><a class="text-link" href="/catalogue/?new=1#designs">Latest designs ↗</a><a class="text-link" href="/catalogue/#designs">All designs ↗</a></div></section><section class="showroom-wrap browse-section" id="designs"><div class="catalogue-controls"><label>Search<input type="search" id="design-search" placeholder="Name, material or style"></label><label>Material<select id="design-category"><option value="">All materials</option><option>Acrylic</option><option>Glass</option><option>Engraved Mandala</option></select></label><p id="design-count" role="status">Loading current designs…</p></div><div class="design-grid">'''+''.join('<article class="design-card" data-current-design="'+d['id']+'"><a href="'+d['productUrl']+'"><img src="'+pic(d)+'" alt="'+E(d['name'])+'" loading="lazy"><h3>'+E(d['name'])+'</h3></a><p>₹'+str(d['pricePerSqIn'])+' / sq in</p></article>' for d in D)+'''</div><p id="design-empty" hidden>No matching designs. Try another material or search.</p></section>'''+(R/'templates/design-dialog.inc').read_text()
page('catalogue/','Current nameplate catalogue','Browse current acrylic, glass and charcoal nameplate designs with custom sizes and transparent square-inch pricing.',body,'<link rel="stylesheet" href="/designs.css?v='+V+'"><script src="/designs.js?v='+V+'" defer></script>')
page('customize/','Design your own nameplate','Personalise a nameplate concept with your name, language, material, colours and lighting.',(R/'templates/customizer.inc').read_text(),'<script src="/app.js?v='+V+'" defer></script><script src="/projects.js?v='+V+'" defer></script>')
print('Rebuilt homepage, catalogue, 7 category pages, 6 collection pages and customizer from',len(D),'active designs.')

# Apply shared chrome and the theme to every existing product and information page.
for target in R.rglob('*.html'):
 text=target.read_text()
 if '<body' not in text:continue
 text=re.sub(r'<body([^>]*)>',lambda m:'<body'+(re.sub(r'class="([^"]*)"',lambda c:'class="'+c[1]+(' nis-luxe' if 'nis-luxe' not in c[1] else '')+'"',m[1]) if 'class=' in m[1] else m[1]+' class="nis-luxe"')+'>',text,count=1)
 text=re.sub(r'<(?:div|a) class="(?:studio-topbar|offer-topline)"[^>]*>.*?</(?:div|a)>\s*(?=<header)', '', text, count=1, flags=re.S)
 text=re.sub(r'<header\b[^>]*>.*?</header>',header,text,count=1,flags=re.S)
 text=re.sub(r'<footer\b[^>]*>.*?</footer>',footer,text,count=1,flags=re.S)
 text=re.sub(r'<link[^>]*href="/(?:storefront-theme|atelier-theme).css[^>]*>','',text)
 text=re.sub(r'<meta name="theme-color"[^>]*>','',text)
 text=text.replace('</head>','<meta name="theme-color" content="#1e73be"></head>')
 text=text.replace('</head>','<link rel="stylesheet" href="/storefront-theme.css?v='+V+'"></head>')
 text=re.sub(r'/shop-theme.js\?v=[^"\s]+','/shop-theme.js?v='+V,text)
 if target==R/'index.html':
  text=text.replace('/storefront-theme.css?v='+V,'/storefront-theme.css?v='+V+'-social').replace('/home.js?v='+V,'/home.js?v='+V+'-social')
 target.write_text(text)
